name: HTML Validation

on:
  push:
    branches:
      - main

jobs:
  validate-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate HTML files
        uses: w3c/html-validator-action@v2
        with:
          files: '*.html'
